deepspeed --module train_cdt \
    --model-path /data/hf_models/Meta-Llama-3.1-8B-Instruct \
    --dataset-paths ./LongAlpaca-Sampled20 \
    --prompt-key instruction \
    --response-key output \
    --sample-counts 16 \
    --sample-counts-eval 2 \
    --max-data-length 128000 \
    --global-batch-size 2 \
    --save-dir ./saved_output \
    --save-name CDT-Llama3.1-8B-Ins \
    --data-cache-dir ./datasetfiles \
    --tensorboard-logdir ./tensorboard \
